name: netscope
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.2
  google_sign_in: ^6.2.2
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.2.5
  xml: ^6.5.0
  provider: ^6.1.2
  process_run: ^0.12.0
  logging: ^1.0.2
  dart_ping: ^8.0.1
  http: ^1.1.0
  intl: ^0.19.0 # Add this line for localization
  cloud_firestore: ^5.0.0
  syncfusion_flutter_gauges: ^27.2.5
  flutter_speedtest: ^0.2.0
  connectivity_plus: ^5.0.2
  image_picker: ^1.0.7
  firebase_storage: ^12.3.6
  firebase_app_check: ^0.3.1+6
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  flutter_riverpod: ^2.4.9
  flag: ^6.0.0
  freezed_annotation: ^2.4.1





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4 # Add this line for unit testing
  build_runner: ^2.4.8
  freezed: ^2.4.6
  integration_test:
    sdk: flutter # Add this line
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/logo2-removebg.png
    - assets/512-background.png