name: netscope
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.2
  google_sign_in: ^6.2.2
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.2.5
  google_maps_webservice: ^0.0.20-nullsafety.5
  provider: ^6.1.2
  process_run: ^0.12.0
  logging: ^1.0.2
  dart_ping: ^8.0.1
  http: ^0.13.5
  intl: ^0.19.0 # Add this line for localization

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.0.16 # Add this line for unit testing
  build_runner: ^2.1.7 # Add this line for code generation
  flutter_localizations:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/logo.png
    - assets/logo2.png
    - assets/map.jpg