// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAFMoJwWKzowziVrztGubtg5VH_7zIMbI',
    appId: '1:331782302853:web:0931ee39fa91ba93aacdec',
    messagingSenderId: '331782302853',
    projectId: 'netscope-ffd10',
    authDomain: 'netscope-ffd10.firebaseapp.com',
    storageBucket: 'netscope-ffd10.firebasestorage.app',
    measurementId: 'G-LKWVWCYG3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALHm1679yNX0Cduvb_aZQQXwXXUtMt4JE',
    appId: '1:331782302853:android:01d220e178c2e4beaacdec',
    messagingSenderId: '331782302853',
    projectId: 'netscope-ffd10',
    storageBucket: 'netscope-ffd10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZLM-FiSJJX1nxZ6BK61RGdr4xe5IjUiI',
    appId: '1:331782302853:ios:ab57d3b485f5842aaacdec',
    messagingSenderId: '331782302853',
    projectId: 'netscope-ffd10',
    storageBucket: 'netscope-ffd10.firebasestorage.app',
    androidClientId: '331782302853-es9ehn095ic14d1138ejdpvrl4b1shro.apps.googleusercontent.com',
    iosClientId: '331782302853-7m0ehfq7s8hva7oaldmi6cdeqirdq44v.apps.googleusercontent.com',
    iosBundleId: 'com.example.netscope',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZLM-FiSJJX1nxZ6BK61RGdr4xe5IjUiI',
    appId: '1:331782302853:ios:ab57d3b485f5842aaacdec',
    messagingSenderId: '331782302853',
    projectId: 'netscope-ffd10',
    storageBucket: 'netscope-ffd10.firebasestorage.app',
    androidClientId: '331782302853-es9ehn095ic14d1138ejdpvrl4b1shro.apps.googleusercontent.com',
    iosClientId: '331782302853-7m0ehfq7s8hva7oaldmi6cdeqirdq44v.apps.googleusercontent.com',
    iosBundleId: 'com.example.netscope',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAFMoJwWKzowziVrztGubtg5VH_7zIMbI',
    appId: '1:331782302853:web:ef1f20f7cf1785edaacdec',
    messagingSenderId: '331782302853',
    projectId: 'netscope-ffd10',
    authDomain: 'netscope-ffd10.firebaseapp.com',
    storageBucket: 'netscope-ffd10.firebasestorage.app',
    measurementId: 'G-Z3B0NHCN9J',
  );

}